apiVersion: blueprints.cloud.google.com/v1alpha1
kind: BlueprintMetadata
metadata:
  name: functions_v1_https_display
spec:
  info:
    title: Firebase Functions v1 HTTPS Function Display
    source:
      repo: https://github.com/inlined/firebase-component-catalog.git
      sourceType: git
      dir: /terraform/modules/functions_v1_https
  ui:
    input:
      variables:
        name:
          name: name
          title: Name
          level: 1
        source_archive:
          name: source_archive
          title: Source Archive GS URL
          regexValidation: ^gs://.*\\.(tgz|zip)$
          validation: The source_archive must be a gs:// URL ending with .tgz or .zip
          level: 1
        extension_id:
          name: extension_id
          title: Extension ID
          level: 2
        project:
          name: project
          title: Project ID
        region:
          name: region
          title: Region
          level: 2
        invokers:
          name: invokers
          title: Invokers
        firebase_admin_config:
          name: firebase_admin_config
          title: Firebase Admin Configuration
        runtime:
          name: runtime
          title: Runtime
        description:
          name: description
          title: Description
        available_memory_mb:
          name: available_memory_mb
          title: Available Memory (MB)
          level: 2
        timeout:
          name: timeout
          title: Timeout (seconds)
          level: 2
        environment_variables:
          name: environment_variables
          title: Environment Variables
        labels:
          name: labels
          title: Labels
        max_instances:
          name: max_instances
          title: Max Instances
          level: 2
        min_instances:
          name: min_instances
          title: Min Instances
          level: 2
        service_account:
          name: service_account
          title: Service Account
        secret_environment_variables:
          name: secret_environment_variables
          title: Secret Environment Variables
        vpc_connector:
          name: vpc_connector
          title: VPC Connector
          level: 2
        vpc_connector_egress_settings:
          name: vpc_connector_egress_settings
          title: VPC Connector Egress Settings
          level: 2
        ingress_settings:
          name: ingress_settings
          title: Ingress Settings
          level: 2
    runtime:
      outputs:
        name:
          visibility: VISIBILITY_ROOT
        id:
          visibility: VISIBILITY_ROOT
        url:
          visibility: VISIBILITY_ROOT
